- hosts: localhost
  connection: local
  ignore_errors: true
  pre_tasks:
    - import_tasks: tasks/facts.yml
      tags:
        - always
  roles:
    - role: markosamuli.linuxbrew
      linuxbrew_use_installer: true
      linuxbrew_init_shell: false
      when: ansible_user_id != 'root'
  tasks:
    - import_tasks: tasks/apt.yml
      become: true
      tags:
        - apt
    - import_tasks: tasks/dconf.yml
      tags:
        - dconf
      when: desktop
    - import_tasks: tasks/brew.yml
      when: ansible_user_id != 'root'
      tags:
        - brew
    - import_tasks: tasks/rust.yml
      tags:
        - rust
    - import_tasks: tasks/dotfiles.yml
      tags:
        - dotfiles
    - import_tasks: tasks/misc.yml
      tags:
        - misc
