- name: Install homebrew packages
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop: "{{ brew_packages }}"
  environment:
    PATH: "/home/linuxbrew/.linuxbrew/bin:{{ ansible_env.PATH }}"
