- name: GNOME detach modal dialog
  dconf:
    key: '/org/gnome/shell/overrides/attach-modal-dialogs'
    value: 'false'

- name: Input source
  dconf:
    key: "/org/gnome/desktop/input-sources/{{ item.key }}"
    value: "{{ item.value }}"
  with_dict:
    xkb-options: "['compose:ralt', 'ctrl:nocaps']"
    per-window: 'true'

- name: Touchpad
  dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/{{ item.key }}"
    value: "{{ item.value }}"
  with_dict:
    tap-to-click: 'true'
    two-finger-scrolling-enabled: 'true'

- name: Button places on left
  dconf:
    key: '/org/gnome/desktop/wm/preferences/button-layout'
    value: '"close,minimize,maximize:"'

- name: Keybinds
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/{{ item.key }}"
    value: "{{ item.value }}"
  with_dict:
    activate-window-menu: "['<Super>space']"
    close: "['<Alt>q']"
    switch-input-source: "['<Alt>space']"
    switch-input-source-backward: "['<Shift><Alt>space']"

- name: Dash to dock
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/{{ item.key }}"
    value: "{{ item.value }}"
  with_dict:
    dock-fixed: "false"
    dock-position: "'BOTTOM'"
    show-mounts-network: "false"
    show-mounts-only-mounted: "true"

- name: Tilling assistant
  dconf:
    key: /org/gnome/shell/extensions/tiling-assistant/enable-tiling-popup
    value: "false"

- name: World clocks
  dconf:
    key: /org/gnome/shell/world-clocks/locations
    value: "[<(uint32 2, <('Eiðar', 'BIEG', true, [(1.1394091075258674, -0.25132741228718347)], [(1.1408635602047243, -0.25045474766118631)])>)>, <(uint32 2, <('Berlin', 'EDDB', true, [(0.91426163401859872, 0.23591034304566436)], [(0.91658875132345297, 0.23387411976724018)])>)>, <(uint32 2, <('Vancouver', 'KVUO', true, [(0.79622405677513375, -2.1407578366569551)], [(0.79654607002212663, -2.1408467960889292)])>)>]"

- name: Panel date format
  dconf:
    key: "/org/gnome/shell/extensions/panel-date-format/format"
    value: "'%F %a %T'"
