---
- name: Clone dotfiles
  git:
    repo: https://github.com/tribela/dotfiles
    dest: ~/git/dotfiles
    update: true
    force: false
  ignore_errors: true
  register: dotfiles_clone

- name: Try update dotfiles
  shell:
    cmd: git -C ~/git/dotfiles pull --rebase --autostash
  when: dotfiles_clone.failed
  changed_when: false

- name: Install dotfiles
  shell:
    cmd: ~/git/dotfiles/install.sh
  changed_when: false
