- name: Check cargo installed
  shell: command -v cargo
  check_mode: false
  register: cargo_installed
  changed_when: false
  failed_when: false

- name: Install cargo
  shell: curl -sSf https://sh.rustup.rs | sh -s -- -y
  when: cargo_installed.rc != 0
  changed_when: cargo_installed.rc != 0
